var GhostExport = require('ghost-export')
var Showdown = require('showdown-ghost')
var markdown = new Showdown.converter().makeHtml // eslint-disable-line
var fs = require('fs-extra')
var mkpath = require('mkpath')
var md5 = require('md5')
var rimraf = require('rimraf')

function replaceAll (string, find, replace) {
  return string.replace(new RegExp(find.replace(/([.*+?^=!:${}()|\[\]\/\\])/g, '\\$1'), 'g'), replace)
}

function matchAll (string, regex, capture_group) {
  var matches = []
  var match = regex.exec(string)

  while (match != null) {
    matches.push(match[capture_group])
    match = regex.exec(string)
  }

  return matches
}

// Create directories
console.log('Cleaning and creating directories...')
rimraf('./+(html|markdown)', function () {
  mkpath.sync('./markdown')
  mkpath.sync('./html')
  mkpath.sync('./html/images')

  // Export markdown
  console.log('Exporting ghost files to markdown...')
  GhostExport({
    source: '.',
    destination: './markdown',
    published: true,
    drafts: false
  }, function (err, count) {
    if (err) throw err

    console.log('Converting markdown into html...')

    // Read markdown files
    var markdown_files = fs.readdirSync('./markdown')
    console.log(markdown_files.length + ' markdown files')

    // Convert & save markdown files
    for (var i = 0; i !== markdown_files.length; i++) {
      var md = fs.readFileSync('./markdown/' + markdown_files[i], {encoding: 'utf-8'})
      var html = markdown(md)

      // Cleanup crap generated by using ghost layout hacks - hey, it kindof works!
      html = replaceAll(html, '<p><a href=""></a><div class="bigPage"></p>', '')
      html = replaceAll(html, '<p></div></p>', '')
      html = replaceAll(html, '<p><a href=""></a><div', '<div')
      html = replaceAll(html, '</div></p>', '</div>')
      html = replaceAll(html, '&amp;', '&')
      html = replaceAll(html, '&amp;', '&')

      // For some reason, showdown doesnt generate images D:
      html = html.replace(/!\[([^\]]*)\]\(([^\)]*)\)/g, '<img src="$2" alt="$1" title="$1"/>')

      // Replace link urls with hashes that are easier to manage & save them in a subdirectory
      var html_links = matchAll(html, new RegExp('<img src="([^"]*)"', 'g'), 1)
      for (var j = 0; j !== html_links.length; j++) {
        var link = html_links[j]
        var ending = link.match(/\..*?$/)[0]
        var hash = 'images/' + md5(link) + ending

        html = replaceAll(html, link, hash)
        fs.copySync('.' + link, './html/' + hash)
      }

      fs.writeFileSync('./html/' + markdown_files[i].replace(/.md$/, '.html'), html)
    }
  })
})
